### PR TITLE
New models for France and Italy

### PR DESCRIPTION
**Pull request by osirello**
Added new models (Opale, Saphir, Black-IT)

### CODE REVIEW

**Review by dkgaraujo — CHANGES_REQUESTED** [review]
Many thanks, @osirello ! Could you please include "Agent-based model" in the "Model type" column?

**Review by osirello — COMMENTED** [review]
@dkgaraujo thanks for your feedback. I edited the model type accordingly.

**Comment by dkgaraujo** [comment]
Apologies @osirello - I meant to ask you to include "Agent-based model" only in the Banda d'Italia model but I forgot to specify. I think the field could be empy for the two French models.

**Review by osirello — COMMENTED** [review]
@dkgaraujo thank you. This should be fixed now.

**Review by dkgaraujo — APPROVED** [review]

**Pull request merged**
